apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/personal-projects9993536/argo-manifests-workshop.git
    path: kubernetes-manifests
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
