apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-volume
  namespace: argocd
  labels:
    type: local
    app: postgres
spec:
  storageClassName: standard
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: '/mnt/data'
